# Site settings
title: "El Cable Amarillo"
description: "Proyecto educativo de código abierto para fomentar el uso de la programación y robótica en los centros educativos."
keywords: "programación, robótica, murcia, primaria, secundaria, educación, centros educativos"

# Collections
collections:
  practicas:
    permalink: /:path:output_ext
    output: true

# Build settings
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
